### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by jyg-107** [Elwinmage/AirZone#3]
Bonjour,

Quand je tape http://<YOUR_IP>:3000/api/v1/integration, avec la bonne adresse, j'ai bien la page de réponse attendue.
par contre une fois le plugin installé (+ chmod +x et restart domoticz), aucun appareil type AirZone n'apparait dans la liste.

"Enter your AirZone IP and let the plugin auto-discover your system." ==> où faut-il rentrer l'IP ?
Faut-il modifier le fichier plugin.py pour y indiquer l'adresse IP du Airzone ?

merci

**Comment by Elwinmage** [comment]
Bonjour, 
Il faut aller dans Configuration>Matériel
Vous choisissez Airzone et c'est dans Adresse.
![airzone](https://github.com/Elwinmage/AirZone/assets/52315693/7e9b2f45-1879-4bcf-9958-f70a92563d6c)
