### ISSUE TITLE
accessibilité en local

### ISSUE THREAD

**Issue by adrienvia** [Elwinmage/AirZone#4]
Bonjour, j'aurai aimé savoir ce qu'il faut faire pour avoir accés en local, j'ai la bonne ip, mais j'ai rien qui se charge, ça me met une erreur quand je veux accéder à http://l'ip:3000/api/v1/integration comment on connait le port d'accès ? même si normalement j'y ai pas touché ^^

merci

**Comment by Elwinmage** [comment]
Bonjour,
quelle est l'erreur reçue lors de la connexion ?
Pour connaitre le port un petit : "nmap <airzone_ip>" doit faire l'affaire. Etes vous certain de l'IP de votre Airzone?

**Comment by adrienvia** [comment]
Bonjour, erreur classique: Ce site est inaccessible192.168.0.91 n'autorise pas la connexion.Voici quelques conseils :Vérifier la connexionERR_CONNECTION_REFUSEEt effectivement avec nmap, j'ai tous les ports fermés sur cette adresse ip...Je sais pas si sur l'appli, ou sur le compte on peut avoir un paramétrage, et si tous les models sont compatibles aussi ...Pour l'adresse IP oui, je suis sur, j'ai que celle ci que je n'avais pas avant, et qui est avec "corporacion empresarial altra" en constructeur...Merci de la réponse en tout casLe 28 nov. 2023 16:29, Elwinmage ***@***.***> a écrit :
Bonjour,
quelle est l'erreur reçue lors de la connexion ?
Pour connaitre le port un petit : "nmap <airzone_ip>" doit faire l'affaire. Etes vous certain de l'IP de votre Airzone?

**Comment by Elwinmage** [comment]
Non tous les modèles ne sont pas compatibles du mode local, d'où le test avant. Désolé pour vous.
